### PR TITLE
Problem: Total paid doesn't include manual... #236

### PR DESCRIPTION
**Pull request by porcellus**
Solution: it now sums up the amount of paid Payments instead of timesheets

### CODE REVIEW

**Comment by gsovereignty** [comment]
@porcellus try to keep your commit messages small in size (ideally <50 chars and hard limit is <70 chars) so that it fits in one line when using git on command line.

**Comment by MadanBhandari** [comment]
@gazhayes why there is two limits  we can just keep one for 50 char and always there is no limit after first line.

**Comment by gsovereignty** [comment]
The 50 character limit in the C4 was originally created because email subject lines in most clients would cut off at 50 chars. Now that this has changed it's not a problem, but there *is* a problem with github UI and also git CLI (or at least the way a lot of people use it). 70 chars seems to work ok, but I'm experimenting with this violation of the C4 before we update the protocol itself.

**Comment by porcellus** [comment]
Oh, sorry, I thought this was 50, I misread something in VIM

**Pull request merged**
