### PR TITLE
Problem: No confirmation dialogs (#73)

### PR DESCRIPTION
**Pull request by anbud**
Solution: Implement confirmation dialogs for all dangerous actions (edit, finish, remove, approve). Let users hide most of the dialogs if they don't want to see them every time. Also, let users reset hidden status of confirmation dialogs on the settings page. Write appropriate client side and server side tests.

### CODE REVIEW

**Comment by anbud** [comment]
Anybody wanna merge me? :D
@gazhayes, @samuelralak

**Comment by samuelralak** [comment]
Yeah sure. Just seeing this

**Comment by samuelralak** [comment]
lol, its been here for 3 days. Apologies man

**Comment by gsovereignty** [comment]
Sorry I've been flying and stuff for the last few days :(

**Comment by anbud** [comment]
Heh, no worries. :)

**Pull request merged**
