### PR TITLE
Problem: Tests are broken

### PR DESCRIPTION
**Pull request by anbud**
Solution: Fix failing tests and CI bugs related to npm package versions.

### CODE REVIEW

**Comment by gsovereignty** [comment]
I'm on phone, can someone clear the cache and see if this works?

**Comment by anbud** [comment]
I've restarted it.
It seems that CI is having some network issues as it's failing while checking if GitHub issue is valid, but only sometimes. They're passing locally without a problem.

**Comment by samuelralak** [comment]
deleted all caches and restarted build

**Comment by anbud** [comment]
They've fixed it, it's passing now. :)

**Pull request merged**
