### PR TITLE
problem:sweetAlerts css is missing resulting in bad UX

### PR DESCRIPTION
**Pull request by AshHimself**
solution: included correct css theme files #107

### CODE REVIEW

**Comment by gsovereignty** [comment]
@AshHimself failing test alert

**Comment by AshHimself** [comment]
Looking

**Comment by AshHimself** [comment]
Oh these are failing due to another issue which @anbud has so kindly offered to fix. #101 

Not related to this by any means.

**Comment by gsovereignty** [comment]
OK merged

**Pull request merged**
