### PR TITLE
Problem : swal working without confirmation #162

### PR DESCRIPTION
**Pull request by MadanBhandari**
Solution : Sweet alert problem fixed by changing swal v2 to v1

### CODE REVIEW

**Comment by anbud** [comment]
@MadanBhandari, do you want to fix failing tests or should I? :)

**Comment by MadanBhandari** [comment]
@anbud I haven't worked much on tests before, I wanna try first. If I didn't succeeded, I'll update here.

I didn't just broke test, I also broke finish issue. I am working on that

**Comment by MadanBhandari** [comment]
@anbud I have updated all the swal popups but still I didn't understand why tests are failing or how to resolve them.

In the meanwhile I am going read more about testing with Mocha and Chai.

If this PR is not good, feel free to close. For now I am leaving this to you.

**Comment by anbud** [comment]
Sorry, I've been in Hungary for the whole day, I'll take a look as soon as I cross the border and get home. :)

**Comment by anbud** [comment]
Ok, I'll merge it and I'll send a PR shortly that fixes failing tests.

**Pull request merged**
