### PR TITLE
problem: unable to request payments

### PR DESCRIPTION
**Pull request by AshHimself**
solution: add ability to specify payment amounts and request for payments #36

### CODE REVIEW

**Comment by AshHimself** [comment]
@anbud - any idea why this is failing?

**Comment by samuelralak** [comment]
`wdio-mocha` wasn't installed for some reason. just restarted the build

**Comment by samuelralak** [comment]
welp, still failing. let me call in the big guns. ping @anbud

**Comment by anbud** [comment]
That's quite weird. I'll check out what's happening and send another PR to fix it. :)

**Comment by anbud** [comment]
Should be fixed in #48.

**Pull request merged**
